title: Islam Rabie # your name (or website title) here
logo: "/images/CloudGamesLogo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  An ensusiasm game developer.
  <br><br>
  I create and help others create extraordinary games.
  <br><br>
  <a href="https://www.linkedin.com/in/islamrabie/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
